export const SET_LINKS_STAtUS = 'SET_LINKS_STATUS';
export const SET_TASK_STATUS = 'SET_TASK_STATUS';
export const SET_TASK_ACTIVE_STATUS = 'SET_TASK_ACTIVE_STATUS';
export const SET_WIDTH_BLOCK = 'SET_WIDTH_BLOCK';
export const SET_PASSWORD_STATUS = 'SET_PASSWORD_STATUS';
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_MODAL_USERS = "TOGGLE_MODAL_USERS";