export const SET_LINKS_STAtUS = 'SET_LINKS_STATUS';
export const SET_TASK_STATUS = 'SET_TASK_STATUS';
export const SET_TASK_ACTIVE_STATUS = 'SET_TASK_ACTIVE_STATUS';
export const SET_WIDTH_BLOCK = 'SET_WIDTH_BLOCK'